vars:  
  
  bg: '111111'
  fg: 'bbbbbb'

  dblack: '393939'
  lblack: '535551'

  dred: 'ca674a'
  lred: 'ea2828'

  dgreen: '96a967'
  lgreen: '87dd32'

  dyellow: 'd3a94a'
  lyellow: 'f7e44d'

  dblue: '5778c1'
  lblue: '6f9bca'

  dpurple: '9c35ac'
  lpurple: 'a97ca4'

  dcyan: '6eb5f3'
  lcyan: '32dddd'

  dwhite: 'a9a9a9'
  lwhite: 'e9e9e7'

files:
  Xdefaults:
    src: home/Xdefaults
    dest: '/home/ben/.Xdefaults'
    delim: '@'

  xinitrc:
    src: home/xinitrc
    dest: '/home/ben/.xinitrc'
    delim: '@'

  vimrc:
    src: home/vimrc
    dest: '/home/ben/.vimrc'
    delim: '@'

  vimperatorrc:
    src: web/vimperatorrc
    dest: '/home/ben/.vimperatorrc'
    delim: '@'

  zshrc:
    src: home/zshrc
    dest: '/home/ben/.zshrc'
    delim: '@'

  scripts:
    src: scripts/
    dest: '/home/ben/.local/bin/'
    delim: '@@'

  mpd:
    src: home/mpd.conf
    dest: '/home/ben/.mpdconf'
    delim: '@@'

  dwm_config:
    src: dwm/config.h
    dest: '/home/ben/Builds/dwm/src/config.h'
    delim: '@'
  dwm_dwm_c:
    src: dwm/dwm.c
    dest: '/home/ben/Builds/dwm/src/dwm-6.0/dwm.c'
    delim: '@@'

  vimperator:
    src: web/colors.vimp
    dest: '/home/ben/.vimperator/colors/custom.vimp'
    delim: '@'

  ncmpcpp:
    src: home/ncmpcpp_config
    dest: '/home/ben/.ncmpcpp/config'
    delim: '@@'

  redshift:
    src: home/redshift.conf
    dest: '/home/ben/.config/redshift.conf'
    delim: '@'

  home_html:
    src: web/home.html
    dest: '/home/ben/.homepage/home.html'
    delim: '@@'

  home_css:
    src: web/home.css
    dest: '/home/ben/.homepage/home.css'
    delim: '@@'

  ghci:
    src: home/ghci
    dest: '/home/ben/.ghci'
    delim: '@@'

scripts:
  
  redwm:
    cmd: '/home/ben/.local/bin/redwm.sh'
    target: dwm

  chmod:
    cmd: 'chmod +x /home/ben/.local/bin/*'
