vars:  
  
  bg: 'fdf6e3'
  fg: '586e75'

  dblack: '073642'
  lblack: '002b36'

  dred: 'dc322f'
  lred: 'cb4b16'

  dgreen: '859900'
  lgreen: '586e75'

  dyellow: 'b58900'
  lyellow: '657b83'

  dblue: '268bd2'
  lblue: '839496'

  dpurple: 'd33682'
  lpurple: '6c71c4'

  dcyan: '2aa198'
  lcyan: '93a1a1'

  dwhite: 'eee8d5'
  lwhite: 'fdf6e3'

files:
  alacritty:
    src: home/alacritty.yml
    dest: '/home/sharafian/.config/alacritty/alacritty.yml'
    delim: '@'

  Xdefaults:
    src: home/Xdefaults
    dest: '/home/sharafian/.Xdefaults'
    delim: '@'

  xinitrc:
    src: home/xinitrc
    dest: '/home/sharafian/.xinitrc'
    delim: '@'

  vimrc:
    src: home/vimrc
    dest: '/home/sharafian/.vimrc'
    delim: '@'

  zshrc:
    src: home/zshrc
    dest: '/home/sharafian/.zshrc'
    delim: '@'

  scripts:
    src: scripts/
    dest: '/home/sharafian/.local/bin/'
    delim: '@@'

  mpd:
    src: home/mpd.conf
    dest: '/home/sharafian/.mpdconf'
    delim: '@@'

  dwm_config:
    src: dwm/config.h
    dest: '/home/sharafian/Builds/dwm/config.h'
    delim: '@'
  dwm_dwm_c:
    src: dwm/dwm.c
    dest: '/home/sharafian/Builds/dwm/dwm.c'
    delim: '@@'

  ncmpcpp:
    src: home/ncmpcpp_config
    dest: '/home/sharafian/.ncmpcpp/config'
    delim: '@@'

  redshift:
    src: home/redshift.conf
    dest: '/home/sharafian/.config/redshift.conf'
    delim: '@'

scripts:
  
  redwm:
    cmd: '/home/sharafian/.local/bin/redwm.sh'
    target: dwm

  chmod:
    cmd: 'chmod +x /home/sharafian/.local/bin/*'
