vars:

  bg: '2E3440'
  fg: 'D8DEE9'

  cursorText: '2E3440'
  cursorColor: 'D8DEE9'

  dblack: '3B4252'
  lblack: '4C566A'

  dred: 'BF616A'
  lred: 'BF616A'

  dgreen: 'A3BE8C'
  lgreen: 'A3BE8C'

  dyellow: 'EBCB8B'
  lyellow: 'EBCB8B'

  dblue: '81A1C1'
  lblue: '81A1C1'

  dpurple: 'B48EAD'
  lpurple: 'B48EAD'

  dcyan: '88C0D0'
  lcyan: '88C0D0'

  dwhite: 'E5E9F0'
  lwhite: 'E5E9F0'

  i3focbr: 'FF8540' #'5E81AC'
  i3focbg: 'FF8540' #'5E81AC'


files:

  # alacritty:
  #   src: config/alacritty.yml
  #   dest: '/home/travis/.config/alacritty/alacritty.yml'
  #   delim: '@'

  # xinitrc:
  #   src: home/xinitrc
  #   dest: '/home/travis/.xinitrc'
  #   delim: '@'

  # xresources:
  #   src: home/xresources
  #   dest: '/home/travis/.Xresources'
  #   delim: '@'

  # i3:
  #   src: config/i3/
  #   dest: '/home/travis/.config/i3/'
  #   delim: '@'

  # polybar:
  #   src: config/polybar
  #   dest: '/home/travis/.config/polybar/config'
  #   delim: '@'

  # rofi:
  #   src: config/rofi
  #   dest: '/home/travis/.config/rofi/config'
  #   delim: '@'

  # gtk-3.0:
  #   src: config/gtk-3.0/settings.ini
  #   dest: '/home/travis/.config/gtk-3.0/settings.ini'
  #   delim: '@'

  scripts:
    src: scripts/
    dest: '/home/travis/bin/'
    delim: '@@'

  git:
    src: git/
    dest: '/home/travis/'
    delim: '@@@@'

  terminator:
    src: terminator/config
    dest: '/home/travis/.config/terminator/config'
    delim: '@@@'

  chrome:
    src: config/chrome-flags.conf
    dest: '/home/travis/.config/chrome-flags.conf'
    delim: '@@@'

  chromium:
    src: config/chromium-flags.conf
    dest: '/home/travis/.config/chromium-flags.conf'
    delim: '@@@'

scripts:

  chmod:
    cmd: 'chmod +x /home/travis/bin/*'
    target: execute

  # rei3road:
  #   cmd: '/home/travis/bin/i3-set-config.sh roadwarrior'
  #   target: i3-roadwarrior

  # rei3office:
  #   cmd: '/home/travis/bin/i3-set-config.sh office'
  #   target: i3-office


  noop:
    cmd: echo Hello
