vars:

files:
  x11:
    src: x11/30-touchpad.conf
    dest: '/etc/X11/xorg.conf.d/30-touchpad.conf'
    delim: '@'

  systemd-logind:
    src: systemd/logind.conf
    dest: '/etc/systemd/logind.conf'
    delim: '@'

  systemd-sleep:
    src: systemd/sleep.conf
    dest: '/etc/systemd/sleep.conf'
    delim: '@'

  prezto:
    src: home/prezto/
    dest: '/usr/lib/prezto/runcoms/'
    delim: '#####'

  grub:
    src: grub/grub
    dest: '/etc/default/grub'
    delim: '@'
  
  grub: 
    src: grub/31_hold_shift
    dest: '/etc/grub.d/31_hold_shift'
    delim: '@'

  tlp: 
    src: tlp/tlp
    dest: '/etc/default/tlp'
    delim: '@'

  bluetooth:
    src: bluetooth/main.conf
    dest: '/etc/bluetooth/main.conf'
    delim: '@'

  pacman:
    src: pacman/pacman.conf
    dest: '/etc/pacman.conf'
    delim: '@'

  pacman:
    src: earlyoom/earlyoom
    dest: '/etc/default/earlyoom'
    delim: '@'


scripts:
  noop:
    cmd: echo Hello
