" Options

" display
syntax on
colorscheme jellybeans
set number

" editing
set expandtab
set tabstop=2
set softtabstop=2
set sw=2
set shiftround
set mouse=a

" Key Bindings

" variables
let mapleader = ","
let maplocalleader = "\\"

" editing vimrc
nnoremap <leader>ve :split ~/Documents/dotfiles/home/vimrc<cr>
nnoremap <leader>vs :!dot<cr><cr>:source $MYVIMRC<cr>

" normal bindings
noremap <c-u> viwU
nnoremap H 0
nnoremap L $
nnoremap J } 
nnoremap K {
vnoremap H 0
vnoremap L $
vnoremap J } 
vnoremap K {
nnoremap <leader>r :r!
nnoremap <leader>f gqip

" surrounding
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>hbi'<esc>lel
nnoremap <leader>( viw<esc>a)<esc>hbi(<esc>lel
nnoremap <leader>{ viw<esc>a}<esc>hbi{<esc>lel
nnoremap <leader>[ viw<esc>a]<esc>hbi[<esc>lel
nnoremap <leader>< viw<esc>a><esc>hbi<<esc>lel

" Automatic Bindings
augroup everything
autocmd!

" buffers
autocmd BufWrite * mkview
autocmd BufRead  * silent loadview

" commenting
autocmd FileType {javascript,c,cpp} nnoremap <buffer> <localleader>c I//<esc>
autocmd FileType {python,ruby,sh,perl} nnoremap <buffer> <localleader>c I#<esc>
autocmd FileType vim nnoremap <buffer> <localleader>c I"<esc>
autocmd FileType {tex,plaintex} nnoremap <buffer> <localleader>c I%<esc>

" compile or run
autocmd FileType {tex,plaintex} nnoremap <buffer> <localleader>r :!pdflatex %<esc>

" End Automatic Bindings
augroup END
