#!/bin/bash

xset +fp /usr/share/fonts/local

# remove caps lock and touchpad taps
setxkbmap -option ctrl:nocaps
synclient MaxTapTime=0

feh --bg-tile /home/ben/Pictures/linen.png

dropbox-cli start &
xcompmgr -c &
pulseaudio --start
mpd &
dwm_bar.rb &
redshift -l 38:-122 &

exec startdwm
