#!/bin/bash

xset +fp /usr/share/fonts/local

# remove caps lock and touchpad taps
# setxkbmap -option ctrl:nocaps
# synclient MaxTapTime=0

# xrandr --output HDMI1 --mode 1600x1200 --output HDMI2 --mode 1920x1080 --left-of HDMI1
# feh --bg-scale /home/ben/Pictures/mountain.png
feh --bg-tile /home/sharafian/Documents/wallpapers/solarizedlightstripes.png

xrandr --dpi 144
xrdb ~/.Xresources
# dropbox-cli start &
# xcompmgr -c &
# pulseaudio --start
# mpd &
# dwm_bar.rb &
# redshift -l 45:122 &
bar &

#sxhkd &
exec startdwm
#exec bspwm -c ~/.config/bspwm/bspwmrc
