#!/bin/bash

xset +fp /usr/share/fonts/local

# remove caps lock and touchpad taps
setxkbmap -option ctrl:nocaps
synclient MaxTapTime=0

feh --bg-scale /home/ben/Pictures/linen.png

xcompmgr -c &
mpd &
dwm_bar.rb &
redshift -l 38:-122 &

exec startdwm
