# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle :compinstall filename '/home/ben/.zshrc'

export fpath=(/home/ben/Documents/prog/cd-memo/zsh $fpath)

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory nomatch notify
unsetopt autocd beep extendedglob
# End of lines configured by zsh-newuser-install

bindkey -e

# Environment Variables
export PATH=$PATH:~/.local/bin
export PATH="/home/ben/.bin:$PATH";
export PATH="/home/ben/.cabal/bin:$PATH";

export PATH="/usr/lib/smlnj/bin:$PATH";
export PATH="/home/ben/.gem/ruby/2.3.0/bin:$PATH";

export XDG_CONFIG_HOME="$HOME/.config"
export EDITOR="vim"
#export BROWSER=/usr/bin/dwb

# Aliases
alias ls="ls --color=auto"
alias vi="vim"
alias spacman="sudo pacman --color always"
alias spamcan="sudo pacman --color always"
alias pacman="pacman --color always"
alias python="python -q"
alias htop="htop -d2"
alias redwm='cd ~/Builds/dwm; updpkgsums; makepkg -efi --noconfirm && killall dwm'
alias bc="bc -q"
alias gdb="gdb -q"
alias glog="git log --pretty=oneline"
alias cobol="cobc -Ox -free"
alias sml="rlwrap sml"
alias ocaml="rlwrap ocaml"
alias pdflatex="pdflatex -interaction=nonstopmode"
alias gadd="git add"
alias gst="git status"

alias mp="mousepad 2>/dev/null >/dev/null"
alias notes="vim ~/Documents/misc/notes.txt"

alias fixpcgen="wmname LG3D "

alias sql="sqlite3 -header -column "
alias sqle="sqlite3 -header -column -echo"

# Prompt
PS1="> "
prompt="> "

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=/home/ben/Builds/cocos2d-x-src/pkg/cocos2d-x-src/opt/cocos2d-x/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH

# Add environment variable COCOS_TEMPLATES_ROOT for cocos2d-x
export COCOS_TEMPLATES_ROOT=/home/ben/Builds/cocos2d-x-src/pkg/cocos2d-x-src/opt/cocos2d-x/templates
export PATH=$COCOS_TEMPLATES_ROOT:$PATH

# Add environment variable ANDROID_SDK_ROOT for cocos2d-x
export ANDROID_SDK_ROOT=/home/ben/Builds/android-sdk-linux
export PATH=$ANDROID_SDK_ROOT:$PATH
export PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH

# Add environment variable NDK_ROOT for cocos2d-x
export NDK_ROOT=/home/ben/Builds/android-ndk-r10e
export PATH=$NDK_ROOT:$PATH

# Add environment variable ANT_ROOT for cocos2d-x
export ANT_ROOT=/usr/bin
export PATH=$ANT_ROOT:$PATH

export GOPATH=~/Builds/go
export PATH=$PATH:~/Builds/go

export SKELTAL_DIR=/home/ben/Documents/dotfiles/skeltal

export CD_MEMO=/home/ben/Documents/dotfiles/home/cd_memo.txt
