#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Customize to your needs...
alias randSecret="~/bin/randomSecret.sh"
alias setup-dotfiles="~/bin/setup_dotfiles.sh" 
alias codiusd-test="sudo DEBUG=* CODIUS_BOOTSTRAP_PEERS=[] CODIUS_HYPER_NOOP=true CODIUS_ROOT=\"/home/travis/codiusDB\" CODIUS_MEMDOWN_PERSIST=true CODIUS_DEV=true  codiusd"
alias moneyd-test="DEBUG=* moneyd --testnet xrp:start"
alias moneyd-real="DEBUG=* moneyd xrp:start"
alias vim=nvim
alias vimdiff='nvim -d'
alias vi=nvim
alias gcloud-update-creds="gcloud container clusters get-credentials primary"
alias kubectl-prisma-prod="kubectl port-forward --cluster gke_stellar-chariot-213418_us-central1-a_primary prisma 4467:4466"
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --smartcase --follow --glob "!.git/*"'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/travis/downloads/google-cloud-sdk-240.0.0-linux-x86_64/google-cloud-sdk/path.zsh.inc' ]; then . '/home/travis/downloads/google-cloud-sdk-240.0.0-linux-x86_64/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/travis/downloads/google-cloud-sdk-240.0.0-linux-x86_64/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/travis/downloads/google-cloud-sdk-240.0.0-linux-x86_64/google-cloud-sdk/completion.zsh.inc'; fi
