#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$PATH:$(yarn global bin)"
# Customize to your needs...
alias randSecret="~/bin/randomSecret.sh"
alias setup-dotfiles="~/bin/setup_dotfiles.sh" 
alias vim=nvim
alias vimdiff='nvim -d'
alias vi=nvim
eval "$(hub alias -s)"
alias gcloud-update-creds="gcloud container clusters get-credentials primary"
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --smartcase --follow --glob "!.git/*"'


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/travis/travis/gcloud/google-cloud-sdk/path.zsh.inc' ]; then . '/home/travis/travis/gcloud/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/travis/travis/gcloud/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/travis/travis/gcloud/google-cloud-sdk/completion.zsh.inc'; fi
