#!/bin/bash
set -e

if [[ $# -ne 3 ]]; then
  echo "usage: $0 <file> <artist> <song>" >&2
  exit
fi

newf="${1%.*}.mp3"

echo "Converting video..."
ffmpeg -i "$1" -codec:v copy -codec:a libmp3lame -q:a 2 "$newf"

echo "Setting Tags..."
id3v2 --artist "$2" "$newf"
id3v2 --song "$3" "$newf"

echo "Cleaning up..."
rm "$1"

mv "./$newf" "/home/$USER/Music/Youtube/$newf"
mpc update >/dev/null

echo "Done!"
