#!/usr/bin/python3 -i

from math import *
import sys
import random
import os

sys.ps1 = "\uE05A "
sys.ps2 = "... "

random.seed(os.urandom(4))

def d(n, l=1):
  return sum([ random.randint(1,n) for x in range(l)])
