#!/bin/bash

ctl_restart() {
  echo "testing netctl restart..."
  sudo ip link set wlp2s0 down
  sudo netctl stop-all
  sudo netctl start wlp2s0-ReedXenia
}

sys_ctl_restart() {
  echo "testing systemctl restart..."
  sudo systemctl stop netctl@wlp2s0-ReedXenia
  sudo systemctl start netctl@wlp2s0-ReedXenia
}

ping_site() {
  ping -c1 -w5 google.com
}

ping_ip() {
  ping -c1 -w5 8.8.8.8
}

test_connect() {
  ping_site && echo "working!" && exit
  ping_ip && echo "dns problem" && exit
}

sys_ctl_restart && test_connect
ctl_restart && test_connect

sudo systemctl status netctl@wlp2s0-ReedXenia
