#!/bin/bash
set -e

if [[ $# -ne 1 ]]; then
  echo "usage: kmark-up <file>" 1>&2
  exit 1
fi

cd $(dirname $1)
file=$(basename $1)
newfile="${file%.*}.html"

echo "renaming $file to $newfile..."
node ~/Documents/prog/js/kmark/kmark.js -h "$file" > "$newfile"

echo "uploading to pierogi.reed.edu:~/html/notes ..."
scp "$newfile" bensharaf@pierogi.reed.edu:~/html/notes/
ssh bensharaf@pierogi.reed.edu 'bash ~/bin/gennotes'

echo "cleaning up..."
rm "$newfile"
