#!/bin/bash
set -e

if [[ $# -ne 1 ]]; then
  echo "usage: kmark <file>" 1>&2
  exit 1
fi

cd $(dirname $1)
file=$(basename $1)
newfile="${file%.*}.html"

node ~/Documents/prog/js/kmark/kmark.js -h "$file" > "$newfile"
