#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "Usage: mark <input>"
  exit 1
fi

cat << EOF
<html>
<head>
  <style>
    #main {
      width: 30em;
      margin: auto;
    }
  </style>
  <script type="text/javascript"
    src="mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
  </script>
</head>
<body>
<div id="main">
EOF

markdown $1 2>&1

cat << EOF
</div>
</body>
</html>
EOF


